apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shoppingmall-api-app
  namespace: cd-system  # ArgoCD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/M4CnCH2Z/webview-app-platform.git
    targetRevision: HEAD
    path: infra/k8s  # 실제 api.yaml, web.yaml 설계도가 있는 폴더
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: staging  # 실제 앱이 배포될 곳
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
