apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shoppingmall-web-app
  namespace: cd-system
  annotations:
    # WEB용 ECR 주소를 감시
    argocd-image-updater.argoproj.io/image-list: my-web=763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    argocd-image-updater.argoproj.io/my-web.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/M4CnCH2Z/webview-app-platform.git
    targetRevision: HEAD
    path: infra/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
