apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shoppingmall-web-app
  namespace: cd-system
spec:
  project: default
  source:
    repoURL: https://github.com/M4CnCH2Z/webview-app-platform.git
    targetRevision: HEAD
    path: infra/k8s # api.yaml과 web.yaml이 같이 들어있는 폴더
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
