apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: api-env
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - APP_RABBIT_ENABLED=false
      - RABBITMQ_ENABLED=false
      - LOG_DIR=/app/logs
      - LOGGING_FILE_PATH=/app/logs
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shoppingmall
      - SPRING_DATASOURCE_USERNAME=root
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api
    newTag: 70cee437e034d729ddf0965c4731657443ca4346
    digest: "sha256:6ba8e4d455eae428a0b9b1eee6f51aefe5fdc45fa37753974dc69912b4f544db"
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    newTag: cad9239565ef30c6894cf15f72920b60684bc42a
    digest: "sha256:e1272fa364da27e38a58ea6131562d966d6ce694953219b238ad7efc2e1ba9a7"
