apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api:latest
        ports:                # <--- image와 같은 라인에 정렬 (8칸 띄움)
        - containerPort: 8080 # <--- ports 아래로 정렬 (10칸 띄움)
---
apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  selector:
    app: my-api
  ports:
    - port: 80
      targetPort: 8080