apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-shopping-api
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: api=763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api
    argocd-image-updater.argoproj.io/api.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-env
        - secretRef:
            name: api-env-secret
        volumeMounts:
        - name: log-dir
          mountPath: /app/logs
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: log-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: staging
spec:
  selector:
    app: my-api
  ports:
    - port: 80
      targetPort: 8080
