apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - web.yaml
  - mysql.yaml

images:
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api
    newTag: 629a154c3555633cf91f1b071874c363ab5213a9
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    newTag: 629a154c3555633cf91f1b071874c363ab5213a9
