apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - web.yaml
  - mysql.yaml

images:
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-api
    newTag: latest
  - name: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    newTag: latest
