apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-shopping-web
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    argocd-image-updater.argoproj.io/web.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-web
        image: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web:latest
        ports:
        - containerPort: 8080
        # --- [추가된 부분: 로그 에러 해결] ---
        env:
        - name: LOGGING_FILE_PATH
          value: /tmp
        - name: LOGGING_FILE_NAME
          value: /tmp/web.log
        # ----------------------------------
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web  # Nginx나 다른 서비스에서 'web'으로 호출 가능
  namespace: staging
spec:
  type: LoadBalancer 
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080 # 앱 포트 8080과 일치시킴