apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-shopping-web
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    argocd-image-updater.argoproj.io/web.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-web
        image: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web:latest
        ports:
        - containerPort: 80
        env:
        - name: LOGGING_FILE_PATH
          value: /app/logs
        volumeMounts:
        # --- [쓰기 권한 에러 해결을 위한 포스트잇 부착] ---
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: log-dir
          mountPath: /app/logs
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
      volumes:
      # --- [임시 쓰기 공간 정의] ---
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: log-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80