apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root1234"
        - name: MYSQL_DATABASE
          value: "shoppingmall"
        volumeMounts: # 데이터 영속화를 위한 볼륨 마운트. 컨테이너 내부의 어느 경로에 마운트할지 지정
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: mysql-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: staging
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
