apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-shopping-web
  namespace: staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: web=763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web
    argocd-image-updater.argoproj.io/web.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: my-web
        image: 763479270202.dkr.ecr.ap-northeast-2.amazonaws.com/shoppingmall-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: LOGGING_FILE_PATH
          value: /app/logs
        - name: SPRING_PROFILES_ACTIVE
          value: staging
        volumeMounts:
        # --- [쓰기 권한 에러 해결을 위한 포스트잇 부착] ---
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: log-dir
          mountPath: /app/logs
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
      volumes:
      # --- [임시 쓰기 공간 정의] ---
      - name: nginx-run
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: log-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: staging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:763479270202:certificate/05bbb19b-66ec-4ba2-a6f3-332dbefb23b7"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "team=m4cnch2z"
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
